import Head from 'next/head';
import { useRouter } from 'next/router';

import { useAuthContext } from '@/pages/components/auth-context-provider';

import styles from '../../../styles/Home.module.css';
import { FormSupplierUpdate } from '../../components/componentsFormsAdmin/form-supplier-update';
import { Navbar } from '../../components/navbar';

export default function Update() {
  const router = useRouter();
  const { query } = router;
  const { id } = query;
  const { user } = useAuthContext();
  return (
    <div className={styles.container}>
      <Head>
        <title>Uparvení dodavatele</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={user} />
      <main className={styles.main}>
        <div>
          <FormSupplierUpdate id={id ? String(id) : ''} />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
