import Head from 'next/head';
import { useRouter } from 'next/router';

import { useSuppDataQuery } from '@/generated/graphql';

import styles from '../../styles/Home.module.css';
import { PackCards } from '../components/Cards/packsCards';
import { SearchAppBar2 } from '../components/navbar2';

// Přepsat!!

// eslint-disable-next-line import/no-default-export
// upravit vypis balicku
// responzivita a sortovani
export default function PacksCards() {
  const suppD = useSuppDataQuery();

  const router = useRouter();
  const { query } = router;
  const { id } = query;

  const selectedSupp = suppD.data?.suplierData.find(
    (actPack: any) => actPack.supplierId === id,
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Upadte package</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchAppBar2 />
      <main className={styles.main}>
        <h1 style={{ textAlign: 'center' }}>
          Welocome to package detail of supplier
        </h1>
        <h2
          style={{
            marginTop: '20px',
            color: '#D67F76',
            fontSize: '30px',
            textAlign: 'center',
          }}
        >
          Packages
        </h2>
        {selectedSupp ? (
          selectedSupp.package ? (
            <div>
              <div
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  flexWrap: 'wrap',
                  maxWidth: '800px',
                }}
              >
                {selectedSupp?.package.map((item: any) => {
                  const keys = Object.keys(item);
                  return keys.map((key: any) => (
                    <div
                      key={key}
                      style={{
                        backgroundColor: '#D67F76',
                        padding: '10px',
                        margin: '10px',
                        borderRadius: '10px',
                      }}
                    >
                      <PackCards
                        key={key}
                        Name={item[key].name_package}
                        Cost={item[key].cost}
                        Weight={item[key].weight}
                        Width={item[key].width}
                        Length={item[key].Plength}
                        Heiht={item[key].height}
                      />
                    </div>
                  ));
                })}
              </div>
            </div>
          ) : (
            <div
              style={{
                textAlign: 'center',
                color: 'orange',
                fontSize: '40px',
                fontWeight: 'bold',
              }}
            >
              Tento dodavatel nemá balíčky
            </div>
          )
        ) : (
          <div
            style={{
              textAlign: 'center',
              color: 'red',
              fontSize: '40px',
              fontWeight: 'bold',
            }}
          >
            Dodavatel nebyl nalezen!!
          </div>
        )}
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
