import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

import { useSuppDataQuery } from '@/generated/graphql';

import { useAuthContext } from '../../copmonents/auth-context-provider';
import { PackCards } from '../../copmonents/Cards/packs-cards';
import { Navbar } from '../../copmonents/navbar';
import styles from '../../styles/Home.module.css';

type Package = {
  [name: string]: {
    weight: number;
    height: number;
    width: number;
    Plength: number;
    name_package: string;
    cost: number;
    supplier_id: string;
  };
};
type SuppData =
  | {
      __typename?: 'QuerySuppD' | undefined;
      sendCashDelivery: string;
      packInBox: string;
      supplierId: string;
      suppName: string;
      pickUp: string;
      delivery: string;
      insurance: number;
      shippingLabel: string;
      foil: string;
      package?: any | undefined;
      location?: any | undefined;
    }
  | undefined;

const IsTherePackage = (data: any) => {
  const packages: Array<Package> = data;
  return Boolean(packages);
};

const IsThereSupp = (data: SuppData) => {
  return !!data;
};

const PageBody = (
  error: boolean,
  warning: boolean,
  dataSupp: SuppData,
  admin: boolean,
  logged: boolean,
) => {
  const packages: Array<Package> = dataSupp?.package;

  if (!logged || !admin) {
    return (
      <div
        style={{
          textAlign: 'center',
          color: 'red',
          fontSize: '30px',
          fontWeight: 'bold',
        }}
      >
        Nejsi admin!!
      </div>
    );
  }

  if (!error) {
    return (
      <div
        style={{
          border: 'solid red',
          borderRadius: '10px',
          color: 'lightblue',
        }}
      >
        <div>
          <img src="/sorry-item-not-found-3328225-2809510.webp" alt="?" />
        </div>
      </div>
    );
  }

  if (!warning) {
    return (
      <div
        style={{
          textAlign: 'center',
          color: 'orange',
          fontSize: '30px',
          fontWeight: 'bold',
        }}
      >
        Tento dodavatel nemá balíčky
      </div>
    );
  }

  return (
    <div style={{ margin: 'auto' }}>
      <div
        style={{
          display: 'flex',
          flexWrap: 'wrap',
          flexDirection: 'row',
          justifyContent: 'center',
          gap: '30px',
        }}
      >
        {packages.map((item) => {
          const key = Object.keys(item)[0];
          return (
            <div
              key={key}
              style={{
                border: '7px solid #0E95EB',
                borderRadius: '10px',
              }}
            >
              <PackCards
                key={key}
                Name={item[key].name_package}
                Cost={item[key].cost}
                Weight={item[key].weight}
                Width={item[key].width}
                Length={item[key].Plength}
                Heiht={item[key].height}
              />
            </div>
          );
        })}
      </div>
    </div>
  );
};

// sortovani
// eslint-disable-next-line import/no-default-export
export default function PacksCards() {
  const suppD = useSuppDataQuery();
  const [body, SetBody] = useState({ element: <div></div> });
  const [admin, SetAdmin] = useState(false);
  const [logged, SetLogin] = useState(false);
  const router = useRouter();

  const { user } = useAuthContext();

  const { query } = router;
  const { id } = query;
  const title = `Vítejte na detailní strance balíčků ${
    user ? user.email ?? '' : ''
  }`;

  useEffect(() => {
    const adminEm = process.env.NEXT_PUBLIC_AdminEm;
    if (user) {
      SetLogin(true);
    }
    if (user?.email === adminEm) {
      SetAdmin(true);
    }
    if (!suppD.loading) {
      const selectedSupp = suppD.data?.suplierData.find(
        (actPack) => actPack?.supplierId === id,
      );

      const errSup = IsThereSupp(selectedSupp);
      const errPack = IsTherePackage(selectedSupp?.package);

      SetBody({
        element: PageBody(errSup, errPack, selectedSupp, admin, logged),
      });
    }
  }, [suppD.loading, suppD.data?.suplierData, logged]);

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={user} />
      <main className={styles.main}>
        <h2
          style={{
            marginTop: '20px',
            color: '#3DA1FF',
            fontSize: '30px',
            textAlign: 'center',
          }}
        >
          Balíčky
        </h2>
        {body.element}
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
