import Head from 'next/head';
import { useRouter } from 'next/router';

import { authUtils } from '@/firebase/auth-utils';

import styles from '../../../styles/Home.module.css';
import { FormPackageUpdate } from '../../components/componentsFormsAdmin/form-package-update';
import { Navbar } from '../../components/navbar2';

export default function Update() {
  const router = useRouter();
  const { query } = router;
  const { id } = query;
  return (
    <div className={styles.container}>
      <Head>
        <title>Upadte package</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={authUtils.getCurrentUser()} />

      <main className={styles.main}>
        <FormPackageUpdate id={id ? String(id) : ''} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
