import Head from 'next/head';
import { useRouter } from 'next/router';

import { useAuthContext } from '@/pages/components/auth-context-provider';

import styles from '../../../styles/Home.module.css';
import { FormPackageUpdate } from '../../components/componentsFormsAdmin/form-package-update';
import { Navbar } from '../../components/navbar';

// eslint-disable-next-line import/no-default-export
export default function Update() {
  const router = useRouter();
  const { query } = router;
  const { id } = query;
  const { user } = useAuthContext();
  return (
    <div className={styles.container}>
      <Head>
        <title>Upravení balíku</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={user} />

      <main className={styles.main}>
        <FormPackageUpdate id={id ? String(id) : ''} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
