import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

import { AdminPageBody } from '@/copmonents/componentBody/adminpage-body';
import { useSuppDataQuery } from '@/generated/graphql';

import { useAuthContext } from '../../copmonents/auth-context-provider';
import { Navbar } from '../../copmonents/navbar';
import styles from '../../styles/Home.module.css';

// eslint-disable-next-line import/no-default-export
export default function Page() {
  const { user } = useAuthContext();
  const suppD = useSuppDataQuery();
  const [body, SetBody] = useState({ element: <div></div> });
  const [admin, SetAdmin] = useState(false);
  const [logged, SetLogin] = useState(false);

  const router = useRouter();
  const { query } = router;
  const { id } = query;

  useEffect(() => {
    const adminId = process.env.NEXT_PUBLIC_ADMIN_ID;
    if (user) {
      SetLogin(true);
    }
    if (user?.uid === adminId) {
      SetAdmin(true);
    }
    if (!suppD.loading) {
      const selectedSupp = suppD.data?.suplierData.find(
        (actPack) => actPack.supplierId === id,
      );

      SetBody({
        element: (
          <AdminPageBody
            data={selectedSupp}
            stylingErr={{
              textAlign: 'center',
              color: 'red',
              fontSize: '40px',
              fontWeight: 'bold',
              margin: 'auto',
            }}
            stylingWarning={{
              textAlign: 'center',
              color: 'orange',
              fontSize: '30px',
              fontWeight: 'bold',
              margin: 'auto',
            }}
            user={user}
            id={selectedSupp?.supplierId}
            adminId={adminId}
          />
        ),
      });
    }
  }, [suppD, logged, admin]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Úprava zásilkové služby/balíků</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={user} />
      <main className={styles.main}>{body.element}</main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
