import Head from 'next/head';

import { authUtils } from '@/firebase/auth-utils';

import styles from '../../styles/Home.module.css';
import { PageFormChangePass } from '../components/componentsForAuth/change-pass';
import { Navbar } from '../components/navbar2';

export default function ChangePassPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Change password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={authUtils.getCurrentUser()} />

      <main className={styles.main}>
        <PageFormChangePass />
      </main>
    </div>
  );
}
