import Head from 'next/head';

import { authUtils } from '@/firebase/auth-utils';

import styles from '../../styles/Home.module.css';
import { FormSupplier } from '../components/componentsFormsAdmin/form-supplier-create';
import { Navbar } from '../components/navbar';

export default function CreateFormSupp() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create supplier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={authUtils.getCurrentUser()} />

      <main className={styles.main}>
        <FormSupplier />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
