import Head from 'next/head';

import styles from '../../styles/Home.module.css';
import { FormPackage } from '../components/componentsFormsAdmin/formPackageCreate';
import { SearchAppBar2 } from '../components/navbar2';

export default function CreateForm() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create package</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchAppBar2 />

      <main className={styles.main}>
        <FormPackage />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
