import Head from 'next/head';

import { useAuthContext } from '../../copmonents/auth-context-provider';
import { FormSupplier } from '../../copmonents/componentsFormsAdmin/form-supplier-create';
import { Navbar } from '../../copmonents/navbar';
import styles from '../../styles/Home.module.css';

// eslint-disable-next-line import/no-default-export
export default function CreateFormSupp() {
  const { user } = useAuthContext();
  return (
    <div className={styles.container}>
      <Head>
        <title>Vytvoření zásilkové služby</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={user} />

      <main className={styles.main}>
        <FormSupplier />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
