import Head from 'next/head';

import styles from '../../styles/Home.module.css';
import { useAuthContext } from '../components/auth-context-provider';
import { PageFormLogin } from '../components/componentsForAuth/login';
import { Navbar } from '../components/navbar';

export default function LoginPage() {
  const { user } = useAuthContext();
  return (
    <div className={styles.container}>
      <Head>
        <title>Přihlášení</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={user} />

      <main className={styles.main}>
        <PageFormLogin />
      </main>
    </div>
  );
}
