import Head from 'next/head';

import { useAuthContext } from '../../copmonents/auth-context-provider';
import { PageRegisterForm } from '../../copmonents/componentsForAuth/register';
import { Navbar } from '../../copmonents/navbar';
import styles from '../../styles/Home.module.css';

// eslint-disable-next-line import/no-default-export
export default function RegisterPage() {
  const { user } = useAuthContext();
  return (
    <div className={styles.container}>
      <Head>
        <title>Registrace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={user} />

      <main className={styles.main}>
        <PageRegisterForm />
      </main>
    </div>
  );
}
