import { getAuth } from 'firebase/auth';
import Head from 'next/head';
import { useEffect, useState } from 'react';

import { authUtils } from '@/firebase/auth-utils';

import styles from '../styles/Home.module.css';
import { useAuthContext } from './components/auth-context-provider';
import { DataGridSupplier } from './components/componentsTables/table-supp';
import { Navbar } from './components/navbar';

const Page = (logged: boolean, admin: boolean) => {
  if (!logged || !admin) {
    return (
      <div
        style={{
          textAlign: 'center',
          color: 'red',
          fontSize: '30px',
          fontWeight: 'bold',
        }}
      >
        Nejsi admin!!!!
      </div>
    );
  }

  return (
    <div>
      <h2
        style={{
          marginTop: '70px',
          color: '#D67F76',
          fontSize: '30px',
        }}
      >
        Table of suppliers
      </h2>
      <DataGridSupplier />
    </div>
  );
};

// eslint-disable-next-line import/no-default-export
export default function AdmPage() {
  const { user, loading } = useAuthContext();
  const [admin, SetAdmin] = useState(false);
  const [logged, SetLogin] = useState(false);
  const P = () => {
    // eslint-disable-next-line @typescript-eslint/no-unused-expressions
    return <div>{loading ?? user?.email}</div>;
  };
  useEffect(() => {
    const Admin = process.env.NEXT_PUBLIC_AdminEm;
    const auth = getAuth();
    if (auth.currentUser) {
      SetLogin(true);
    }
    if (auth.currentUser?.email === Admin) {
      SetAdmin(true);
    }
  }, [logged, admin]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create supplier with packages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={authUtils.getCurrentUser()} />

      <main className={styles.main}>
        <h1>Welocome to admin interface</h1>
        <h2>{P()}</h2>
        {Page(logged, admin)}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
