import Head from 'next/head';
import { useEffect, useState } from 'react';

import { AdminPageBody } from '@/copmonents/componentBody/admpage-body';

import { useAuthContext } from '../copmonents/auth-context-provider';
import { Navbar } from '../copmonents/navbar';
import styles from '../styles/Home.module.css';

// eslint-disable-next-line import/no-default-export
export default function AdmPage() {
  const { user } = useAuthContext();
  const [admin, SetAdmin] = useState(false);
  const [logged, SetLogin] = useState(false);

  useEffect(() => {
    const adminId = process.env.NEXT_PUBLIC_ADMIN_ID;

    if (user) {
      SetLogin(true);
    }
    if (user?.uid === adminId) {
      SetAdmin(true);
    }
  }, [logged, admin]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Admin page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={user} />
      <main className={styles.main}>
        {<AdminPageBody logged={logged} admin={admin} />}
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
