import Head from 'next/head';
import React, { useState } from 'react';

import { useMutSuitableSuppMutation } from '@/generated/graphql';

import styles from '../styles/Home.module.css';
import { SearchAppBar2 } from './components/navbar2';

export default function Home() {
  const [dataS, SetData] = useState([]);
  // eslint-disable-next-line @typescript-eslint/no-unsafe-call
  const [suitableSupp] = useMutSuitableSuppMutation();

  const Res = (dataSui: any) => {
    return (
      <div>
        <p>{dataSui.length}</p>
        {dataSui.map((itm: any, index: number) => (
          <div key={index}>
            {Object.values(itm).map((value: any, idx: number) => (
              <p key={idx}>{value}</p>
            ))}
          </div>
        ))}
      </div>
    );
  };
  const HandleForm = async () => {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call
    const res = await suitableSupp({
      variables: {
        Width: 7,
        Weight: 15,
        Height: 6,
        Length: 7,
      },
    });
    console.log('ssss', res.data?.BingoSupPac?.suitable);
    // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
    const data = JSON.parse(res.data?.BingoSupPac?.suitable ?? 'NIC');
    console.log('dddddddddddddddddddddata', data);
    SetData(data);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchAppBar2 />

      <main className={styles.main}>
        {Res(dataS)}
        <button onClick={HandleForm}>odeslat</button>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
