import Head from 'next/head';
import React, { useState } from 'react';

import {
  useMutSuitableSuppMutation,
  useSuppDataQuery,
} from '@/generated/graphql';

import styles from '../styles/Home.module.css';
import stylesF from '../styles/stylesForm/styleForms.module.css';
import { ResSuppCard } from './components/Cards/resSupp';
import { FormChooseSup } from './components/formChooseSupp';
import { Navbar } from './components/navbar2';

const parseIntReliable = (numArg: string) => {
  const min = 1;
  if (numArg.length > 0) {
    const parsed = Number.parseInt(numArg, 10);
    if (parsed === 0) {
      // eslint-disable-next-line max-depth
      if (numArg.replaceAll('0', '') === '') {
        return 0;
      }
    } else if (Number.isSafeInteger(parsed) && Number(parsed) > min) {
      return parsed;
    }
  }
  return false;
};

const Res = (dataSui: [], allSupp: any) => {
  const SuitableSupps: Array<any> = [];
  // eslint-disable-next-line @typescript-eslint/no-unsafe-call
  console.log('co tam je', SuitableSupps);
  console.log('co tam jeee2', dataSui);
  console.log('objecty', dataSui);
  // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-return
  dataSui.forEach((itm: any) => {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call
    SuitableSupps.push({
      // eslint-disable-next-line @typescript-eslint/no-unsafe-call
      dataS: allSupp.data?.suplierData.find((item: any) => {
        return item.supplierId === itm.suppId;
      }),
      cost: itm.cost,
      packName: itm.name,
    });
    console.log('sorted val', itm.suppId);
    console.log('supplier', allSupp.data?.suplierData);
  });
  console.log('ssuitabel', SuitableSupps);

  // eslint-disable-next-line @typescript-eslint/no-unsafe-return
  return SuitableSupps ?? [];
};

// eslint-disable-next-line consistent-return
const RenderSupp = (
  dataFromResolver: any,
  QueryData: any,
  dataFromForm: object,
) => {
  // alert(JSON.stringify(Res(dataFromResover, QueryData)));
  if (!QueryData.loading && !QueryData.error && QueryData.data) {
    // eslint-disable-next-line array-callback-return
    return Res(dataFromResolver, QueryData).map((itm: any) => (
      <div key={itm.dataS.supplierId}>
        <ResSuppCard
          packName={itm.packName}
          price={itm.cost}
          delivery={itm.dataS.delivery}
          folie={itm.dataS.foil}
          insurance={itm.dataS.insurance}
          packInBox={itm.dataS.packInBox}
          pickUp={itm.dataS.pickUp}
          sendCash={itm.dataS.sendCashDelivery}
          shippingLabel={itm.dataS.shippingLabel}
          name={itm.dataS.suppName}
          sId={itm.dataS.supplierId}
          dataFrPage={dataFromForm}
        />
      </div>
    ));
  }
};

const Valid = (
  hmotnostarg: string,
  costarg: string,
  delkaarg: string,
  vyskaarg: string,
  sirkaarg: string,
  // eslint-disable-next-line unicorn/consistent-function-scoping, consistent-return
) => {
  if (!parseIntReliable(hmotnostarg)) {
    return new Error('Invalid argument, expext number bigger than 0');
  }

  if (!parseIntReliable(costarg)) {
    return new Error('Invalid argument, expext number bigger than 0');
  }

  if (!parseIntReliable(delkaarg)) {
    return new Error('Invalid argument, expext number bigger than 0');
  }

  if (!parseIntReliable(vyskaarg)) {
    return new Error('Invalid argument, expext number bigger than 0');
  }

  if (!parseIntReliable(sirkaarg)) {
    return new Error('Invalid argument, expext number bigger than 0');
  }
};

export default function SuitableSupp() {
  const [dataS, SetData] = useState([]);
  const [width, SetWidth] = useState('');
  const [height, SetHeight] = useState('');
  const [weight, SetWeight] = useState('');
  const [plength, SetLength] = useState('');
  const [placeFrom, SetPlceForm] = useState('');
  const [placeTo, SetPlceTo] = useState('');
  const [cost, SetCost] = useState('');

  // eslint-disable-next-line @typescript-eslint/no-unsafe-call
  const [suitableSupp] = useMutSuitableSuppMutation();
  const suppData = useSuppDataQuery();

  const HandleForm = async () => {
    const valid = Valid(weight, cost, plength, height, width)?.message;
    if (valid) {
      alert(valid);
    } else {
      const result = await suitableSupp({
        variables: {
          Width: Number(width),
          Weight: Number(weight),
          Height: Number(height),
          Length: Number(plength),
          Mz: placeFrom,
          Mdo: placeTo,
          Cost: Number(cost),
        },
      });

      if (result.data?.BingoSupPac?.suitable) {
        const data = JSON.parse(result.data?.BingoSupPac?.suitable);
        SetData(data);
      } else {
        // eslint-disable-next-line no-alert
        alert(result.data?.BingoSupPac?.message);
      }
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <FormChooseSup
          onChangeSirka={(e) => SetWidth(e.toString())}
          onChangeVyska={(e) => SetHeight(e.toString())}
          onChangeHmotnost={(e) => SetWeight(e.toString())}
          onChangeDelka={(e) => SetLength(e.toString())}
          onChangeCena={(e) => SetCost(e.toString())}
          onChangeDo={(e) => SetPlceTo(e.toString())}
          onChangeZ={(e) => SetPlceForm(e.toString())}
          buttonEl={
            <button className={stylesF.crudbtn} onClick={HandleForm}>
              odeslat
            </button>
          }
        />
        {RenderSupp(dataS, suppData, {
          dataFrForm: {
            width,
            height,
            weight,
            plength,
            placeFrom,
            placeTo,
          },
        })}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
