import Head from 'next/head';
import Link from 'next/link';
import React, { useState } from 'react';

import { useResSupplierMutation, useUserDataQuery } from '@/generated/graphql';

import stylesM from '../styles/Main.module.css';
import { useAuthContext } from './components/auth-context-provider';
import { CardOffer } from './components/Cards/cardToIndexPage';
import { SearchAppBar2 } from './components/navbar2';

export default function Home() {
  const userD = useUserDataQuery();
  const [val, SetVal] = useState('');
  const [intV, SetintVal] = useState('');

  // eslint-disable-next-line @typescript-eslint/no-unsafe-call
  const [suitableSupp] = useResSupplierMutation();
  const { user, loading } = useAuthContext();
  const s = userD.data?.userdata;
  const EmUS = () => {
    return s?.map((em) => (
      <p key={em.email}>
        {em.email} : {em.dataUs} : {em.historyId} : {em.supplierId}
      </p>
    ));
  };
  const P = () => {
    // eslint-disable-next-line @typescript-eslint/no-unused-expressions
    return <div>{user?.email}</div>;
  };
  // const Res = (dataSui: any) => {
  //   return (
  //     <div>
  //       <p>{dataSui.length}</p>
  //       {dataSui.map((itm: any, index: number) => (
  //         <div key={index}>
  //           {Object.values(itm).map((value: any, idx: number) => (
  //             <p key={idx}>{value}</p>
  //           ))}
  //         </div>
  //       ))}
  //     </div>
  //   );
  // };
  const HandleForm = async () => {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call
    await suitableSupp({
      variables: {
        Value: val,
        valInt: Number(intV),
      },
    })
      .then((result) => {
        alert(
          `${result.data?.Predict.value ?? result.data?.Predict.message} ${
            result.data?.Predict.intVal ?? 0
          }`,
        );
      })
      .catch((error) => {
        // console.log('jjjerr', error.message);
        alert(error);
      });
    // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
    // SetErrMsg(res.data?.Predict.message ?? 'vse ok');
    // alert(res.errors.message);
    // alert(err);
  };
  return (
    <div className={stylesM.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchAppBar2 />

      <main>
        <div className={stylesM.body1}>
          <div className={stylesM.item1}>
            <img className={stylesM.suppImg} src="/ImgSupp.png" alt="" />
          </div>

          <div className={stylesM.item2}>
            <div>
              <h1 className={stylesM.body1Napis}>BingoBalík</h1>
              <p className={stylesM.body1Odstavec}>
                Stánka, která pomáha najít vaše Bingo balíky podle vaších
                představ s nejvhodnějším dodavatelem
              </p>
            </div>
          </div>
        </div>

        <div className={stylesM.body2}>
          <h1 className={stylesM.body2Napis}>Co vám nabízíme?</h1>
          <CardOffer
            img="lupa2.png"
            label="Nejvhodnější balíky"
            description="Zde si podle vašich parametrů můžete objednat svůj vhodný balík dle výšky, šířky, délky hmostnosti toho, co tam dáte a lokace "
          />

          <CardOffer
            img="history2.jpg"
            label="Historie"
            description="Historie objednávek, které si uživatel může prohlédnout i s nimi manipulovat. Lze je zpětně dokončit i smazat"
          />

          <CardOffer
            img="kopie.jpg"
            label="Objednání"
            description="Zde si lze i objednat balík u dopravce, který vám nejvíce vyhovuje "
          />
        </div>

        <div className={stylesM.body4}>
          <div className={stylesM.item7}>
            <img src="/confused.webp" alt="" className={stylesM.itmImg2} />
          </div>
          <div className={stylesM.item8}>
            <h1 className={stylesM.body4Napis}>Jak zde najdete svůj balík?</h1>
            <p className={stylesM.body4Odstavec}>
              Stačí kliknout na taličítko
              <Link key="chooseSup-page" href={'/chooseSup-page'}>
                <button className={stylesM.itemBtn}>Nejvhodnější balík</button>
              </Link>
              , se kterým najdete svůj vysněný balík
            </p>
          </div>
        </div>

        <div className={stylesM.body5}>
          <div className={stylesM.item9}>
            <h1 className={stylesM.body5Napis}>Sparáva účtu a informace</h1>
            <p className={stylesM.body5Odstavec}>
              Spravovat účet lze tu též a na stránce k tomu určené najdete i
              vaši historii objednávek, lze i změnit heslo a email. Kliknutím na
              tlačítko po obrázkama se dostanete na stránku vašeho účtu
            </p>
          </div>

          <div className={stylesM.item10}>
            <img src="/s2.png" alt="" className={stylesM.itemImg} />
          </div>
          <div className={stylesM.item11}>
            <img src="/pngegg.png" alt="" className={stylesM.itemImg} />
          </div>
          <div className={stylesM.item12}>
            <button className={stylesM.itemBtn}>Spravovat účet</button>
          </div>
        </div>
      </main>
    </div>
  );
}
