import Head from 'next/head';
import React from 'react';

import styles from '../styles/Home.module.css';
import { StepperComp } from './components/multiForm';
import { SearchAppBar2 } from './components/navbar2';

export default function Stepper() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchAppBar2 />

      <main className={styles.main}>
        <div>
          <StepperComp />
        </div>
      </main>
    </div>
  );
}
