import Head from 'next/head';
import React from 'react';

import styles from '../styles/Home.module.css';
import { useAuthContext } from './components/auth-context-provider';
// import { StepperComp } from './components/multiForm';
import { Navbar } from './components/navbar';

export default function Stepper() {
  const { user } = useAuthContext();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={user} />

      <main className={styles.main}>
        {/* <div>
          <StepperComp />
        </div> */}
      </main>
    </div>
  );
}
