import Head from 'next/head';

import styles from '../styles/Home.module.css';
import { SearchAppBar } from './components/navbar';
import { PageRegisterForm } from './components/register';

export default function RegisterPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchAppBar />

      <main className={styles.main}>
        <PageRegisterForm />
      </main>
    </div>
  );
}
