import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

import { authUtils } from '@/firebase/auth-utils';
import { useHistoryDataQuery } from '@/generated/graphql';

import styles from '../styles/Home.module.css';
import { Navbar } from './components/navbar2';

const buttonPart = (name: string) => {
  if (name === 'dpd') {
    return (
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-around',
        }}
      >
        <button
          style={{
            width: '80px',
            height: '60px',
            borderRadius: '10px',
            backgroundColor: 'red',
            color: 'white',
            fontWeight: 'bold',
            border: ' solid red',
          }}
        >
          Delete
        </button>
        <Link href="https://zrukydoruky.dpd.cz/">
          <button
            style={{
              width: '80px',
              height: '60px',
              borderRadius: '10px',
              backgroundColor: '#23B8FA',
              color: 'white',
              fontWeight: 'bold',
              border: ' solid #23B8FA',
            }}
          >
            Přejít na stránku
          </button>
        </Link>
      </div>
    );
  }

  return (
    <button
      style={{
        width: '80px',
        height: '60px',
        borderRadius: '10px',
        backgroundColor: 'red',
        color: 'white',
        fontWeight: 'bold',
        border: ' solid red',
      }}
    >
      Delete
    </button>
  );
};
export default function UserPage() {
  const email = authUtils.getCurrentUser()?.email;
  // eslint-disable-next-line @typescript-eslint/no-unsafe-call
  const hitoryD = useHistoryDataQuery();
  return (
    <div className={styles.container}>
      <Head>
        <title>User page {email}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <h1>Moznosti pro uzivatele</h1>
        <div
          style={{
            display: 'flex',
            gap: '40px',
            margin: '20px',
          }}
        >
          <button
            onClick={authUtils.logout}
            style={{
              width: '100px',
              height: '50px',
              borderRadius: '10px',
              backgroundColor: '#48BEFA',
              color: 'white',
              fontWeight: 'bold',
              border: 'solid #89D7FA',
            }}
          >
            Odhlaseni
          </button>
          <button
            style={{
              width: '100px',
              height: '50px',
              borderRadius: '10px',
              backgroundColor: '#236EFA',
              color: 'white',
              fontWeight: 'bold',
              border: 'solid #89D7FA',
            }}
          >
            Zmena email
          </button>
          <button
            style={{
              width: '100px',
              height: '50px',
              borderRadius: '10px',
              backgroundColor: '#49E9FA',
              color: 'white',
              fontWeight: 'bold',
              border: 'solid #89D7FA',
            }}
          >
            Zmena hesla
          </button>
        </div>
        <h1 style={{ textAlign: 'center' }}>History {email}</h1>
        {
          // eslint-disable-next-line @typescript-eslint/no-unsafe-call
          hitoryD.data?.historyUserData.map((historyItm) => {
            return (
              <div
                key={historyItm.historyId}
                style={{
                  backgroundColor: 'wheat',
                  borderRadius: '10px',
                  margin: '20px',
                  border: '5px solid #FAEA88',
                }}
              >
                <div>
                  <h1 style={{ textAlign: 'center' }}>
                    {historyItm.historyId}
                  </h1>
                </div>
                <div
                  style={{
                    display: 'flex',
                    gap: '40px',
                    margin: '20px',
                  }}
                >
                  <div>
                    <strong>Data z formulare</strong>
                    <p>Vyska: {historyItm.dataForm.height}</p>
                    <p>Sirka: {historyItm.dataForm.width}</p>
                    <p>Delka: {historyItm.dataForm.plength}</p>
                    <p>Hmotnost: {historyItm.dataForm.weight}</p>
                    <p>Odkud: {historyItm.dataForm.placeFrom}</p>
                    <p>Kam: {historyItm.dataForm.placeTo}</p>
                  </div>
                  <div>
                    <strong>Data dodavatele</strong>
                    <p>Jmeno: {historyItm.suppData.name}</p>
                    <p>Pojisteni: {historyItm.suppData.insurance}</p>
                    <p>Doruceni: {historyItm.suppData.delivery}</p>
                    <p>Vyzvednuti: {historyItm.suppData.pickup}</p>
                    <p>V boxu: {historyItm.suppData.packInBox}</p>
                    <p>Štítek: {historyItm.suppData.shippingLabel}</p>
                    <p>Na dobírku: {historyItm.suppData.sendCashDelivery}</p>
                    <p>Ve folii: {historyItm.suppData.foil}</p>
                    <p>Celkova cena: {historyItm.suppData.cost}</p>
                  </div>

                  <div>
                    <strong>Balíček</strong>
                    <p>Oznaceni: {historyItm.suppData.packName}</p>
                  </div>
                  {buttonPart(historyItm.suppData.name)}
                </div>
              </div>
            );
          })
        }
      </main>
    </div>
  );
}
