import Head from 'next/head';
import { useRouter } from 'next/router';

import { FormPackage } from '@/pages/components/componentsFormsAdmin/form-package-create';

import styles from '../../../styles/Home.module.css';
import { Navbar } from '../../components/navbar2';

export default function CreateForm() {
  const { query } = useRouter();
  const { id } = query;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create package</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <FormPackage id={String(id)} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
